/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

const { describe, it, before } = require('node:test')
const assert = require('node:assert')

const Seneca = require('seneca')

const MeetupProvider = require('../dist/meetup-provider')
const MeetupProviderDoc = require('../dist/MeetupProvider-doc')

const SenecaMsgTest = require('seneca-msg-test')
const { Maintain } = require('@seneca/maintain')

const { SEED } = require('./seed')

const BasicMessages = require('../dist-test/basic.messages')


describe('meetup-provider', () => {

  it('happy', async () => {
    assert.notEqual(MeetupProvider, undefined)
    assert.notEqual(MeetupProviderDoc, undefined)

    const seneca = await makeSeneca()

    assert.partialDeepStrictEqual(
      await seneca.post('sys:provider,provider:meetup,get:info'),
      {
        ok: true,
        name: 'meetup',
      },
    )
  })


  it('messages', async () => {
    const seneca = await makeSeneca()
    await SenecaMsgTest(seneca, BasicMessages)()
  })


  it('sdk-export', async () => {
    const seneca = await makeSeneca()
    const sdk = seneca.export('MeetupProvider/sdk')()

    assert.equal(typeof sdk.Event, 'function')
  })


  it('event-needs-group_urlname', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/meetup/event').list$({}),
      /group_urlname is required/,
    )
  })


  it('event-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/meetup/event')
      .list$({ group_urlname: 'group_urlname0' })

    assert.equal(list.length, 2)
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/meetup/event',
    )
    assert.equal(list[0].group_urlname, 'group_urlname0')
  })


  it('event-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/meetup/event')
      .load$({ group_urlname: 'group_urlname0', id: 'event0' })

    assert.equal(found.id, 'event0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/meetup/event',
    )
  })


  it('event-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/meetup/event')
      .load$({ group_urlname: 'group_urlname0', id: 'nosuchevent' })

    assert.equal(missing, null)
  })


  it('maintain', async () => {
    const exclude = []

    // check_default proves the default branch is main by looking for
    // [branch "main"] in .git/config. Only a branch checkout records that
    // section: a pull_request build checks out the merge ref, and the
    // publish build checks out a tag as a detached HEAD. Neither says
    // anything about what the default branch is, so skip rather than fail.
    if ('pull_request' === process.env.GITHUB_EVENT_NAME ||
        'tag' === process.env.GITHUB_REF_TYPE) {
      exclude.push('check_default')
    }

    // url_pkgjson locates package.json by comparing process.cwd() + '/package.json'
    // against a path found with Filehound. On Windows those are the same file
    // spelt with different separators, so the url is never read.
    if ('win32' === process.platform) {
      exclude.push('url_pkgjson')
    }

    await Maintain({ exclude })
  })

})


// Default to the SDK's offline mock transport, seeded from ./seed.
async function makeSeneca(pluginopts) {
  pluginopts = pluginopts || { test: true, testopts: SEED }

  const seneca = Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('env', {
      // Declared so the provider convention is exercised, and defaulted so
      // the suite runs with nothing configured.
      var: {
        $MEETUP_APIKEY: '',
      },
    })
    .use('provider', {
      provider: {
        meetup: {
          keys: {
            apikey: { value: '$MEETUP_APIKEY' },
          },
        },
      },
    })
    .use(MeetupProvider, pluginopts)

  return seneca.ready()
}
