/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

// Seed data for the SDK's offline mock transport, so the entity tests
// exercise real code paths without a server.
const SEED = {
  entity: {
    event: {
      event0: {"dateTime":"dateTime0","eventUrl":"eventUrl0","id":"event0","status":"status0","title":"title0","group_urlname":"group_urlname0"},
      event1: {"dateTime":"dateTime1","eventUrl":"eventUrl1","id":"event1","status":"status1","title":"title1","group_urlname":"group_urlname0"},
    },
  },
}

module.exports = { SEED }
